// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7ca2dcb8-537b-4932-8afb-c1e982eac34f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_jnaBYT6Sa",
    "aws_user_pools_web_client_id": "76emst8jh5haj7rod11mgu1tks",
    "oauth": {},
    "aws_user_files_s3_bucket": "gatsbyblogcontentprod-prod",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
